### ISSUE TITLE
Package loads Blaze, Jquery on client

### ISSUE THREAD

**Issue by pcmaffey** [meteor/galaxy-seo-package#6]
After removing and reinstalling all my packages one by one, this is the one that requires jquery and blaze and other templating packages on client.

Possible to use without?

**Comment by stolinski** [comment]
Having this same issue. I've spent all morning tracking down this dependency.

**Comment by MKRazz** [comment]
This is because the package relies on `templating`. I cloned the package into my project and replaced `templating` with `static-html` and it appears to be working fine without adding all those blaze/jquery/templating packages.

I considered doing a pull request for this but then it isn't appropriate for people using blaze. Maybe including them both as `weak` dependencies would work? Not sure if there's a scenario where you wouldn't have `templating` nor `static-html`.

Another option could be to use `server-render` to append it to the head, but maybe that's overkill. Though this method could allow for a new Meteor setting / ENV variable to include `window.prerenderReady = false;` automatically.

**Comment by coagmano** [comment]
Using server-render is probably the way to go.

But, it looks like adding the meta tag is not needed any more?
https://stackoverflow.com/a/17190878/992964

**Comment by filipenevola** [comment]
Yes @coagmano, according to this article this tag is not supported anymore https://developers.google.com/search/docs/ajax-crawling/docs/getting-started

**Comment by filipenevola** [comment]
This should be fixed in the version 3.2.2 published today
